### ISSUE TITLE
启动服务端报错

### ISSUE THREAD

**Issue by YangYongZhi** [Tencent/Metis#12]
执行命令时报错
python /data/Metis/app/controller/manage.py runserver {ip}:{port}

```python /root/Metis/app/controller/manage.py runserver 192.168.8.8:18654
receive SIGCHLD
child process %s exit with exitcode %s 4721 0
current process has no existing unwaited-for child processes.
handle SIGCHLD end
receive SIGCHLD
child process %s exit with exitcode %s 4722 0
current process has no existing unwaited-for child processes.
handle SIGCHLD end
receive SIGCHLD
child process %s exit with exitcode %s 4724 0
current process has no existing unwaited-for child processes.
handle SIGCHLD end
receive SIGCHLD
child process %s exit with exitcode %s 4732 0
current process has no existing unwaited-for child processes.
handle SIGCHLD end
Performing system checks…

Unhandled exception in thread started by <function check_errors.<locals>.wrapper at 0x7f7075217488>
Traceback (most recent call last):
  File "/root/django/django/utils/autoreload.py", line 225, in wrapper
    fn(*args, **kwargs)
  File "/root/django/django/core/management/commands/runserver.py", line 117, in inner_run
    self.check(display_num_errors=True)
  File "/root/django/django/core/management/base.py", line 390, in check
    include_deployment_checks=include_deployment_checks,
  File "/root/django/django/core/management/base.py", line 377, in _run_checks
    return checks.run_checks(**kwargs)
  File "/root/django/django/core/checks/registry.py", line 72, in run_checks
    new_errors = check(app_configs=app_configs)
  File "/root/django/django/core/checks/urls.py", line 40, in check_url_namespaces_unique
    all_namespaces = _load_all_namespaces(resolver)
  File "/root/django/django/core/checks/urls.py", line 57, in _load_all_namespaces
    url_patterns = getattr(resolver, 'url_patterns', [])
  File "/root/django/django/utils/functional.py", line 37, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/root/django/django/urls/resolvers.py", line 559, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/root/django/django/utils/functional.py", line 37, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/root/django/django/urls/resolvers.py", line 552, in urlconf_module
    return import_module(self.urlconf_name)
  File "/opt/rh/rh-python36/root/usr/lib64/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/root/Metis/app/controller/settings/urls.py", line 18, in <module>
    from api import views as api_views
  File "/root/Metis/app/controller/api/views.py", line 20
    except Exception, ex:
                    ^
SyntaxError: invalid syntax
```

由于需要安装最新的django，必须使用python３.６，所以目前使用的是python　３.６。
是否是执行该启动服务脚本时必须用python２.７？

**Comment by YangYongZhi** [comment]
哦，谢谢，那么文档中django的版本，我觉得可以加上“目前只支持1.x版本”。
例如：
git clone https://github.com/django/django.git
git checkout 1.11.16
