### ISSUE TITLE
uwsgi部署失败

### ISSUE THREAD

**Issue by amu0324** [Tencent/Metis#27]
命令：uwsgi --http :9005 --chdir /root/metis/app/ --wsgi-file /root/metis/app/controller/settings/wsgi.py --master --processes 4
错误如下：
mapped 364600 bytes (356 KB) for 4 cores
*** Operational MODE: preforking ***
Traceback (most recent call last):
  File "/root/metis/app/controller/settings/wsgi.py", line 16, in <module>
    application = get_wsgi_application()
  File "/usr/lib/python2.7/site-packages/django/core/wsgi.py", line 13, in get_wsgi_application
    django.setup(set_prefix=False)
  File "/usr/lib/python2.7/site-packages/django/__init__.py", line 22, in setup
    configure_logging(settings.LOGGING_CONFIG, settings.LOGGING)
  File "/usr/lib/python2.7/site-packages/django/conf/__init__.py", line 53, in __getattr__
    self._setup(name)
  File "/usr/lib/python2.7/site-packages/django/conf/__init__.py", line 41, in _setup
    self._wrapped = Settings(settings_module)
  File "/usr/lib/python2.7/site-packages/django/conf/__init__.py", line 97, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/lib64/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named settings.settings
unable to load app 0 (mountpoint='') (callable not found or import error)
*** no app loaded. going in full dynamic mode ***
uWSGI running as root, you can use --uid/--gid/--chroot options

**Comment by amu0324** [comment]
uwsgi.ini文件如下可以正常启动
[uwsgi]
http = :9005
socket = :9006
chdir = /root/metis/app/controller/
wsgi-file = settings/wsgi.py
master = true
processes = 4
pidfile = uwsgi.pid
daemonize = uwsgi.log

**Comment by Jesyjun** [comment]
这个ini配置django可以起来，不过页面读取不到数据库内容，请问一下nginx里面是怎么配置的？
