### ISSUE TITLE
python manage.py runserver {ip}:{port} 启动报错

### ISSUE THREAD

**Issue by javaDeveloperBook** [Tencent/Metis#57]
Performing system checks...

Unhandled exception in thread started by <function wrapper at 0x7f69aa77e410>
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/django/utils/autoreload.py", line 226, in wrapper
    fn(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/django/core/management/commands/runserver.py", line 121, in inner_run
    self.check(display_num_errors=True)
  File "/usr/lib/python2.7/site-packages/django/core/management/base.py", line 374, in check
    include_deployment_checks=include_deployment_checks,
  File "/usr/lib/python2.7/site-packages/django/core/management/base.py", line 361, in _run_checks
    return checks.run_checks(**kwargs)
  File "/usr/lib/python2.7/site-packages/django/core/checks/registry.py", line 81, in run_checks
    new_errors = check(app_configs=app_configs)
  File "/usr/lib/python2.7/site-packages/django/core/checks/urls.py", line 14, in check_url_config
    return check_resolver(resolver)
  File "/usr/lib/python2.7/site-packages/django/core/checks/urls.py", line 24, in check_resolver
    for pattern in resolver.url_patterns:
  File "/usr/lib/python2.7/site-packages/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/lib/python2.7/site-packages/django/urls/resolvers.py", line 313, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/usr/lib/python2.7/site-packages/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/lib/python2.7/site-packages/django/urls/resolvers.py", line 306, in urlconf_module
    return import_module(self.urlconf_name)
  File "/usr/lib64/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/data/expense-api/Metis/app/controller/settings/urls.py", line 18, in <module>
    from api import views as api_views
  File "/data/expense-api/Metis/app/controller/api/views.py", line 8, in <module>
    from app.service.time_series_detector.anomaly_service import *
**ImportError: No module named app.service.time_series_detector.anomaly_service**

**Comment by Jesyjun** [comment]
我也是

**Comment by javaDeveloperBook** [comment]
/Metis/app/controller/manage.py 加入一行代码，即可：

#!/usr/bin/env python
import os
import sys
**sys.path.append(os.getcwd())**
print(os.getcwd())


if __name__ == "__main__":
    os.environ.setdefault("DJANGO_SETTINGS_MODULE", "settings.settings")
    try:
        from django.core.management import execute_from_command_line
    except ImportError:
        # The above import may fail for some other reason. Ensure that the
        # issue is really that Django is missing to avoid masking other
        # exceptions on Python 2.
        try:
            import django
        except ImportError:
            raise ImportError(
                "Couldn't import Django. Are you sure it's installed and "
                "available on your PYTHONPATH environment variable? Did you "
                "forget to activate a virtual environment?"
            )
        raise
    execute_from_command_line(sys.argv)


执行命令： sudo python /data/Metis/app/controller/manage.py runserver {ip}:{port}  进行启动

估计是路径问题，这样可以解决

**Comment by Jesyjun** [comment]
是python虚拟环境问题 已经解决

**Comment by xttyawei** [comment]
> 是python虚拟环境问题 
怎么解决的？

**Comment by Jesyjun** [comment]
简单一点export PYTHONPATH=/你存放的目录/Metis:$PYTHONPATH也可以加到~/.bash_profile或者virtualenv配置一下，也就是python添加虚拟环境
