### ISSUE TITLE
启动的时候报错

### ISSUE THREAD

**Issue by x-future** [Tencent/Metis#95]
Unhandled exception in thread started by <function wrapper at 0x2b272ad85488>
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/django/utils/autoreload.py", line 226, in wrapper
    fn(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/django/core/management/commands/runserver.py", line 121, in inner_run
    self.check(display_num_errors=True)
  File "/usr/lib/python2.7/site-packages/django/core/management/base.py", line 374, in check
    include_deployment_checks=include_deployment_checks,
  File "/usr/lib/python2.7/site-packages/django/core/management/base.py", line 361, in _run_checks
    return checks.run_checks(**kwargs)
  File "/usr/lib/python2.7/site-packages/django/core/checks/registry.py", line 81, in run_checks
    new_errors = check(app_configs=app_configs)
  File "/usr/lib/python2.7/site-packages/django/core/checks/urls.py", line 14, in check_url_config
    return check_resolver(resolver)
  File "/usr/lib/python2.7/site-packages/django/core/checks/urls.py", line 24, in check_resolver
    for pattern in resolver.url_patterns:
  File "/usr/lib/python2.7/site-packages/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/lib/python2.7/site-packages/django/urls/resolvers.py", line 313, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/usr/lib/python2.7/site-packages/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/lib/python2.7/site-packages/django/urls/resolvers.py", line 306, in urlconf_module
    return import_module(self.urlconf_name)
  File "/usr/lib64/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/opt/metis/app/controller/settings/urls.py", line 18, in <module>
    from api import views as api_views
  File "/opt/metis/app/controller/api/views.py", line 11, in <module>
    from app.service.time_series_detector.detect_service import *
  File "/opt/metis/app/service/time_series_detector/detect_service.py", line 17, in <module>
    from time_series_detector.algorithm import xgboosting
  File "/opt/metis/time_series_detector/algorithm/xgboosting.py", line 13, in <module>
    from time_series_detector.feature import feature_service
  File "/opt/metis/time_series_detector/feature/feature_service.py", line 11, in <module>
    import statistical_features
  File "/opt/metis/time_series_detector/feature/statistical_features.py", line 11, in <module>
    import tsfresh.feature_extraction.feature_calculators as ts_feature_calculators
  File "/usr/lib/python2.7/site-packages/tsfresh/__init__.py", line 33, in <module>
    from tsfresh.convenience.relevant_extraction import extract_relevant_features
  File "/usr/lib/python2.7/site-packages/tsfresh/convenience/relevant_extraction.py", line 7, in <module>
    from tsfresh.feature_extraction import extract_features
  File "/usr/lib/python2.7/site-packages/tsfresh/feature_extraction/__init__.py", line 5, in <module>
    from tsfresh.feature_extraction.extraction import extract_features
  File "/usr/lib/python2.7/site-packages/tsfresh/feature_extraction/extraction.py", line 17, in <module>
    from tsfresh.feature_extraction import feature_calculators
  File "/usr/lib/python2.7/site-packages/tsfresh/feature_extraction/feature_calculators.py", line 27, in <module>
    from statsmodels.tools.sm_exceptions import MissingDataError
  File "/usr/lib64/python2.7/site-packages/statsmodels/tools/__init__.py", line 1, in <module>
    from .tools import add_constant, categorical
  File "/usr/lib64/python2.7/site-packages/statsmodels/tools/tools.py", line 8, in <module>
    from statsmodels.compat.python import lzip, lmap
  File "/usr/lib64/python2.7/site-packages/statsmodels/compat/__init__.py", line 1, in <module>
    from statsmodels.tools._testing import PytestTester
  File "/usr/lib64/python2.7/site-packages/statsmodels/tools/_testing.py", line 11, in <module>
    from statsmodels.compat.pandas import assert_equal
  File "/usr/lib64/python2.7/site-packages/statsmodels/compat/pandas.py", line 4, in <module>
    import numpy as np
  File "/usr/lib64/python2.7/site-packages/statsmodels/compat/numpy.py", line 46, in <module>
    NP_LT_114 = LooseVersion(np.__version__) < LooseVersion('1.14')
AttributeError: 'module' object has no attribute '__version__'

**Comment by zhangshengdong** [comment]
和我一样

**Comment by wolfparticle** [comment]
我也遇到这个问题，这应该是个bug.
![image](https://user-images.githubusercontent.com/11906788/80349870-78252080-88a2-11ea-806a-fd5c9dc749c5.png)

**Comment by guowhite** [comment]
statsmodels 版本需要降到0.9.0，但是你出了这个问题 很大概率是启动不成功的，建议还是docker大法

**Comment by x-future** [comment]
貌似都没人修了

**Comment by lilihongjava** [comment]
> statsmodels 版本需要降到0.9.0，但是你出了这个问题 很大概率是启动不成功的，建议还是docker大法

降到0.9.0就行了，是这个原因

**Comment by Liyaozhou** [comment]
[root@hlink1 uweb]# cnpm run build

> metis-web@1.0.0 build /root/Metis/uweb
> node lib/uw-frame/lib/cli/build

clean-webpack-plugin: /root/Metis/uweb/dist has been removed.
ℹ ｢atl｣: Using typescript@2.9.2 from typescript
ℹ ｢atl｣: Using tsconfig.json from /root/Metis/uweb/lib/uw-frame/lib/config/tsconfig.json
ℹ ｢atl｣: Checking started in a separate process...
✖ ｢atl｣: Checking finished with 1 errors
